sudo: required
language: ruby
rvm:
- 2.3
install: bin/install.sh
script: bin/script.sh
before_install:
- openssl aes-256-cbc -K $encrypted_2f79aeb0e40d_key -iv $encrypted_2f79aeb0e40d_iv
  -in TestKey.pem.enc -out ~/.ssh/TestKey.pem -d
env:
  global:
  - secure: C51O/ld7t8OsRjyWEWEM4p6tT/B2K4vrMNkuvd63fKd3+OtFKVH6gB49i4VnolrHyCfhgnW4CThquWbIMuEi2xSNcHUWDHGnQwgPEtS7MBYIDMWzgJ/N2rZTwtTxxvUTecYthN3INiAXf4lwbnJn/QUqNsOFcepwEtTfs1S/We5rHgd8F2+qSw37QD3tJCAwRV3UHUqu8RPOn9K6VsMWvOKyN9DTu2utx9rVrujQadNYUS9Osea/oJndL32KhMBV0NF6GmWiI8JT25lXTTXaXV4xeTmGyZZRXE0aXUya1k19PgIozSPtHG9HMZ8oS7ZPCOIouo7Vleml2Z5GfEL0O/gwg0MaXVPq0s+mFQArySm7URdQ1qbV6U/9Yp9gU3FjgcwtT22kvrIFn4JMTDfA8pi0+de9NK0eW1b/qW7IVAtCOEpRgxQT1FOgnRj+WEP0atWwcYkpf0rRFyEdZT51dx6MXObh1BhbtIgqM85TZlasm6W8rYsgVHe3zK+0IK+nHjUT9YkIy6Hi/uOmczo94KmME2oW6XaeDIvNQeKzK8BrHLZ/N2MZuZkFBgT7KMbyoo4z7TA/R12cynD4jXCddbqVJ/dWMThx6929PRPRBm27xlPfNGfP/twrxvB442zaOZQ+8qcIQ3N1CZpb8PryJmvA7er6LZ5diQy5Ih8n5Ks=
  - secure: bF534e3vwLIZXMIy3q8av8X3E0QZRflR0/pFGaH4KP+Q34E5aV25Zp6+hYj0bKYzVk5tJN+l8lzeU1cBqN2d/bMbrN8qSJcEU73fxdr0cDbtV7Ff2tZZ6UehfqxEPJFk1Yjz3tiZ9ud2iMJPP/RXl/j6DCIjHY6lN2tiHhXgUvOOIXP8yMU0NUk0V60oBnvmuJr/Frf9Z2rSBnCorNkxBb+FrB9lQVkjEdEKS+s5xm98/Q/LPxwSHFMcw9u/mun+ORB+AtvlAnMX5Kb63TABMi6gXKiefvdB8DntsD8LApj+qElXbVLv04PaErKArDc3qD/Au49h/ba1Es3NliMXWDILZSUaE4aLG4iTxrcnUzRLQH008h6yoL7jeHxzREE9o/i6W5UMcY5EKFBxoS27x3e8L58tlV+DA8ARmVX23TfOsWG1A5Z3abU48FEu4KoIjf8n3R56muWOrT/QXJ+QB9SjCYsQjZOPoGEZQNisCg/ADHYw1kjMcVKTdsFzhlibm6VeNvaiOOir+GaYyPYgQYr9Avic+y7+Jlkoz+U3GDJtC0No5z1MGYPdAZw/KJ6VBS1iWRP9lpC9CzzMDe612BE32kKehdG8u4RkESL0PjjTJkQGCkBQe8MRjJPtv7UPxz2A8uXubnDcVn43Ze3IY6IjEmYiSg9pIWadC5NaJvs=
