sudo: required
language: ruby
rvm:
- 2.3
install: bin/install.sh
script: bin/script.sh
before_install:
- openssl aes-256-cbc -K $encrypted_2f79aeb0e40d_key -iv $encrypted_2f79aeb0e40d_iv
  -in TestKey.pem.enc -out ~\/.ssh/TestKey.pem -d
- openssl aes-256-cbc -K $encrypted_2f79aeb0e40d_key -iv $encrypted_2f79aeb0e40d_iv
  -in TestKey.pem.enc -out ~/.ssh/TestKey.pem -d
